# Generated by Django 2.2.7 on 2020-02-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepost',
            name='postName',
        ),
        migrations.AddField(
            model_name='leftmenu',
            name='menuUrl',
            field=models.CharField(default='about', max_length=30),
        ),
    ]
