# Generated by Django 2.2.7 on 2020-02-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200229_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftmenu',
            name='menuUrl',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sitepost',
            name='postUrl',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
