# Generated by Django 3.0.4 on 2020-03-07 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200229_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsName', models.CharField(max_length=100)),
                ('newsText', models.TextField()),
                ('datePublished', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='leftmenu',
            name='menuUrl',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sitepost',
            name='leftMenu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.LeftMenu'),
        ),
    ]
