# Generated by Django 2.2.7 on 2020-03-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='urlmenu',
        ),
        migrations.AddField(
            model_name='equipment',
            name='postUrl',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
