# Generated by Django 2.2.7 on 2020-03-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200308_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='figureCaption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='equipment',
            name='longDescription',
            field=models.TextField(blank=True),
        ),
    ]
